---
# tasks file for install_apache2

- name: INSTALL APACHE2 AND PHP-MOD
  apt: name={{ item }} update_cache=yes state=latest
  loop: [ 'apache2', 'libapache2-mod-php' ]  
         
- name: CREATE NEW DIR FOR WEBSITE 
  file:
    path: "/var/www/{{ host }}"
    state: directory
    owner: "{{ user }}"
    mode: '0775'
        
- name: COPY NEW CONFIG FOR VIRTUALHOST APACHE2
  template:
    src: "files/website.conf.j2"
    dest: "/etc/apache2/sites-available/{{ config }}"
  notify: RELOAD APACHE2
      
- name: COPY DEMO PHP PAGE
  template:
    src: "files/phpinfo.php.j2"
    dest: "/var/www/{{ host }}/phpinfo.php"
    owner: "{{ user }}"
    mode: '0775'
         
- name: ENABLE NEW WEBSITE
  shell: /usr/sbin/a2ensite "{{ config }}"
  notify: RELOAD APACHE2

- name: DISABLE DEFAULT CONFIG VIRTUALHOST APACHE2 
  shell: /usr/sbin/a2dissite 000-default.conf
  when: disable_default
  notify: RELOAD APACHE2
